'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  Filter, ArrowUpRight, ArrowDownRight,
  CheckCircle, XCircle, Loader2, RefreshCw, Activity, X,
} from 'lucide-react';
import { useToast } from '@/components/Toast';
import { formatUSD } from '@/lib/utils';
import { format } from 'date-fns';

interface SignalData {
  id: string;
  agentId: string;
  agentName: string;
  timestamp: string;
  market: string;
  marketSlug: string;
  tokenId: string;
  conditionId: string;
  side: 'BUY' | 'SELL';
  price: number;
  size: number;
  sizeUSDC: number;
  confidence: number;
  reasoning: string;
  status: string;
  orderId?: string;
  errorMessage?: string;
}

export default function SignalsPage() {
  const [signals, setSignals] = useState<SignalData[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterSide, setFilterSide] = useState<string>('all');
  const [filterAgent, setFilterAgent] = useState<string>('all');
  const { addToast } = useToast();

  const fetchSignals = useCallback(async (manual = false) => {
    try {
      if (manual) setRefreshing(true);
      // Use the run endpoint which scans markets and returns all data
      const res = await fetch('/api/agents/run', { method: 'POST' });
      if (res.ok) {
        const data = await res.json();
        setSignals(data.signals || []);
        if (manual) {
          addToast('success', 'Refreshed', `${(data.signals || []).length} signals loaded from ${data.result?.marketsScanned || 0} markets`);
        }
      }
    } catch (err) {
      console.error('Failed to fetch signals:', err);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [addToast]);

  useEffect(() => {
    fetchSignals();
    const interval = setInterval(() => fetchSignals(), 60000);
    return () => clearInterval(interval);
  }, [fetchSignals]);

  const agentNames = [...new Set(signals.map(s => s.agentName))];

  const filtered = signals.filter(s => {
    if (filterStatus !== 'all' && s.status !== filterStatus) return false;
    if (filterSide !== 'all' && s.side !== filterSide.toUpperCase()) return false;
    if (filterAgent !== 'all' && s.agentName !== filterAgent) return false;
    return true;
  });

  const statusCounts = {
    generated: signals.filter(s => s.status === 'generated').length,
    executing: signals.filter(s => s.status === 'executing').length,
    executed: signals.filter(s => s.status === 'executed').length,
    failed: signals.filter(s => s.status === 'failed').length,
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-end justify-between">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-800 tracking-tight">Signals</h1>
          <p className="text-sm text-slate-500 mt-1">Live trading signals generated by AI agents</p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => fetchSignals(true)}
            disabled={refreshing}
            className="btn-secondary flex items-center gap-2 py-2 px-3.5"
          >
            {refreshing ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
            {refreshing ? 'Scanning...' : 'Refresh'}
          </button>
          <span className="text-xs text-slate-500 font-medium">{signals.length} total signals</span>
        </div>
      </div>

      {/* Status Summary */}
      <div className="grid grid-cols-4 gap-4">
        <div className="card p-4 border-l-4 border-amber-400">
          <p className="text-[10px] text-slate-400 font-medium uppercase">Generated</p>
          <p className="text-2xl font-bold text-amber-600">{statusCounts.generated}</p>
        </div>
        <div className="card p-4 border-l-4 border-blue-400">
          <p className="text-[10px] text-slate-400 font-medium uppercase">Executing</p>
          <p className="text-2xl font-bold text-blue-600">{statusCounts.executing}</p>
        </div>
        <div className="card p-4 border-l-4 border-emerald-400">
          <p className="text-[10px] text-slate-400 font-medium uppercase">Executed</p>
          <p className="text-2xl font-bold text-emerald-600">{statusCounts.executed}</p>
        </div>
        <div className="card p-4 border-l-4 border-red-400">
          <p className="text-[10px] text-slate-400 font-medium uppercase">Failed</p>
          <p className="text-2xl font-bold text-red-600">{statusCounts.failed}</p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-3 flex-wrap">
        <div className="flex items-center gap-2 text-slate-500">
          <Filter className="w-4 h-4" />
          <span className="text-xs font-semibold uppercase tracking-wider">Filters</span>
        </div>
        <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} className="input-dark text-sm">
          <option value="all">All Statuses</option>
          <option value="generated">Generated</option>
          <option value="executing">Executing</option>
          <option value="executed">Executed</option>
          <option value="failed">Failed</option>
        </select>
        <select value={filterSide} onChange={(e) => setFilterSide(e.target.value)} className="input-dark text-sm">
          <option value="all">All Sides</option>
          <option value="buy">Buy</option>
          <option value="sell">Sell</option>
        </select>
        <select value={filterAgent} onChange={(e) => setFilterAgent(e.target.value)} className="input-dark text-sm">
          <option value="all">All Agents</option>
          {agentNames.map(name => (
            <option key={name} value={name}>{name}</option>
          ))}
        </select>
        {(filterStatus !== 'all' || filterSide !== 'all' || filterAgent !== 'all') && (
          <button
            onClick={() => { setFilterStatus('all'); setFilterSide('all'); setFilterAgent('all'); }}
            className="text-xs text-blue-600 hover:text-blue-700 font-medium flex items-center gap-1"
          >
            <X className="w-3 h-3" /> Clear
          </button>
        )}
        <span className="text-xs text-slate-500 font-medium ml-auto">{filtered.length} signals</span>
      </div>

      {/* Loading */}
      {loading && (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
          <span className="ml-3 text-slate-500">Scanning markets and generating signals...</span>
        </div>
      )}

      {/* Empty State */}
      {!loading && signals.length === 0 && (
        <div className="card p-12 text-center">
          <Activity className="w-12 h-12 text-slate-300 mx-auto mb-3" />
          <p className="text-sm font-semibold text-slate-600">No signals generated yet</p>
          <p className="text-xs text-slate-400 mt-1">Click Refresh to scan markets and generate signals</p>
        </div>
      )}

      {/* Signals Table */}
      {!loading && filtered.length > 0 && (
        <div className="card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="text-left px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Time</th>
                  <th className="text-left px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Agent</th>
                  <th className="text-left px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Market</th>
                  <th className="text-left px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Side</th>
                  <th className="text-right px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Price</th>
                  <th className="text-right px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Size (USDC)</th>
                  <th className="text-right px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Confidence</th>
                  <th className="text-left px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Status</th>
                  <th className="text-left px-4 py-3 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Reasoning</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filtered.map(sig => (
                  <tr key={sig.id} className="hover:bg-slate-50 transition-colors">
                    <td className="px-4 py-3 text-xs text-slate-500 font-mono whitespace-nowrap">
                      {format(new Date(sig.timestamp), 'MMM dd HH:mm:ss')}
                    </td>
                    <td className="px-4 py-3">
                      <span className="text-xs font-semibold text-slate-700">{sig.agentName}</span>
                    </td>
                    <td className="px-4 py-3">
                      <span className="text-xs text-slate-600 max-w-[250px] truncate block" title={sig.market}>
                        {sig.market}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`inline-flex items-center gap-1 text-xs font-bold ${
                        sig.side === 'BUY' ? 'text-emerald-600' : 'text-red-600'
                      }`}>
                        {sig.side === 'BUY' ? <ArrowUpRight className="w-3 h-3" /> : <ArrowDownRight className="w-3 h-3" />}
                        {sig.side}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-right text-xs font-mono font-semibold text-slate-700">
                      ${sig.price.toFixed(3)}
                    </td>
                    <td className="px-4 py-3 text-right text-xs font-mono text-slate-600">
                      ${sig.sizeUSDC.toFixed(2)}
                    </td>
                    <td className="px-4 py-3 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <div className="w-12 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                          <div
                            className={`h-full rounded-full ${
                              sig.confidence >= 0.8 ? 'bg-emerald-500' :
                              sig.confidence >= 0.6 ? 'bg-amber-500' : 'bg-red-500'
                            }`}
                            style={{ width: `${sig.confidence * 100}%` }}
                          />
                        </div>
                        <span className="text-xs font-bold text-slate-500">{(sig.confidence * 100).toFixed(0)}%</span>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold ${
                        sig.status === 'executed' ? 'bg-emerald-50 text-emerald-700' :
                        sig.status === 'executing' ? 'bg-blue-50 text-blue-700' :
                        sig.status === 'failed' ? 'bg-red-50 text-red-700' :
                        sig.status === 'generated' ? 'bg-amber-50 text-amber-700' :
                        'bg-slate-100 text-slate-600'
                      }`}>
                        {sig.status === 'executed' && <CheckCircle className="w-3 h-3" />}
                        {sig.status === 'failed' && <XCircle className="w-3 h-3" />}
                        {sig.status === 'executing' && <Loader2 className="w-3 h-3 animate-spin" />}
                        {sig.status.toUpperCase()}
                      </span>
                      {sig.errorMessage && (
                        <p className="text-[10px] text-red-500 mt-1 max-w-[150px] truncate" title={sig.errorMessage}>
                          {sig.errorMessage}
                        </p>
                      )}
                    </td>
                    <td className="px-4 py-3">
                      <span className="text-[11px] text-slate-500 max-w-[200px] truncate block" title={sig.reasoning}>
                        {sig.reasoning}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
